// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	IsVerified            bool               `json:"is_verified"`
	VerificationToken     pgtype.Text        `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}
